# Generated by Django 3.1.6 on 2021-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('email', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
