# Generated by Django 3.1.6 on 2021-02-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0002_auto_20210206_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='review',
            new_name='reviews',
        ),
    ]
