# Generated by Django 3.1.6 on 2021-02-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0003_auto_20210206_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='reviews',
            new_name='review',
        ),
    ]
