# Generated by Django 3.1.6 on 2021-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0004_auto_20210206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img',
            field=models.ImageField(default='images/apple.jpg', upload_to='images/'),
        ),
    ]
