# Generated by Django 3.1.6 on 2021-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0005_client_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='img',
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.FileField(default='images/apple.jpg', upload_to='images/'),
        ),
    ]
