# Generated by Django 3.1.6 on 2021-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0006_auto_20210206_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='images/apple.jpg', upload_to='images/'),
        ),
    ]
