# Generated by Django 3.1.6 on 2021-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0007_auto_20210206_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(default='images/apple.jpg', upload_to='images/'),
        ),
    ]
